
server:
  port: 8090
mymybatis-plus:
  configuration:
    call-setters-on-nulls: true
    #解决，查询返回结果含null没有对应字段值问题

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    com.daizhihua.sample.dao : debug
spring:

  boot:
    admin:
      client:
        url: http://localhost:8000
        instance:
          name: ReactiveCrud
  datasource:
    url: jdbc:mysql://39.104.177.194:3306/daizhihua?serverTimezone=UTC&characterEncoding=utf8&useUnicode=true&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 3
      min-idle: 5
      max-active: 20
      #配置超时时间
      max-wait: 3000
      #配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      max-evictable-idle-time-millis: 900000
      validation-query: SELECT
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      # 打开PSCache，并且指定每个连接上PSCache的大小
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      filters: stat,wall,log4j
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      # 合并多个DruidDataSource的监控数据
      #spring.datasource.useGlobalDataSourceStat=true
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connect-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=10000
      web-stat-filter:
        #是否启用StatFilter默认值false
        enabled: false
          # 拦截所有的
        url-pattern: /*
        # 排除一些不必要的url，比如*:js,/jslib/*等等:
        exclusions:  "*.js,*.gif,*.jpg,*.png,*.css,*.ico, /druid/*"
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        # 界面上有一个重置功能 执行这个操作之后，会导致所有计数器清零，重新计数 建议false
        reset-enable: false
          # 登录的后台的用户名,密码
        login-username: admin
        login-password: admin
        # 访问控制，可以配置allow和deny这两个参数
        # 配置格式 ip或者ip/子网掩码(24) 例如   192.168.2.112 ,192.168.2.112/24
        # 注意 由于匹配规则不支持IPV6，配置了allow或者deny之后，会导致IPV6无法访问。
        # allow:
        # deny:

  mvc:
    static-path-pattern: /resources/**


  thymeleaf:
    prefix:  classpath:/templates/