
server:
  port: 8090

spring:
  datasource:
    url: jdbc:mysql://47.92.68.127:3306/huanyuenwei?serverTimezone=UTC&characterEncoding=utf8&useUnicode=true&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  mvc:
    static-path-pattern: /resources/**

  thymeleaf:
    prefix:  classpath:/templates/