
server:
  port: 8090


logging:
  level:
    com.daizhihua.sample.dao : debug
spring:

  datasource:
    url: jdbc:mysql://39.104.177.194:3306/daizhihua?serverTimezone=UTC&characterEncoding=utf8&useUnicode=true&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  mvc:
    static-path-pattern: /resources/**

  thymeleaf:
    prefix:  classpath:/templates/